auto: true
server: true
markdown: kramdown

prose:
  rooturl: '_posts'
  siteurl: 'http://julianzeiler.github.io/'
  media: 'img'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blog"
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
